### ISSUE TITLE
Import PoniardClassifier is raising import error 

### ISSUE THREAD

**Issue by asodha991** [rxavier/poniard#1]
After successfully installing Poniard, while importing classifier or regressor it is raising the below error.
I have successfully installed the latest version. I have the python 3.9.7 version.

Error----------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8096/3658873288.py in <module>
----> 1 from poniard import PoniardClassifier

~\anaconda3\lib\site-packages\poniard\__init__.py in <module>
      1 from poniard._version import __version__
----> 2 from poniard.estimators.classification import PoniardClassifier
      3 from poniard.estimators.regression import PoniardRegressor
      4 
      5 

~\anaconda3\lib\site-packages\poniard\estimators\classification.py in <module>
      4 from sklearn.base import ClassifierMixin, TransformerMixin
      5 from sklearn.pipeline import Pipeline
----> 6 from sklearn.model_selection import (
      7     BaseCrossValidator,
      8     BaseShuffleSplit,

ImportError: cannot import name 'BaseShuffleSplit' from 'sklearn.model_selection' (C:\Users\asodh\anaconda3\lib\site-packages\sklearn\model_selection\__init__.py)

**Comment by rxavier** [comment]
Hi. This looks like the preinstalled scikit-learn in conda is older. Could you show the output of 

```
import sklearn

sklearn.__version__
```

**Comment by asodha991** [comment]
Thanks you , Rafael for valueable time.
I have updated scikit-learn and it has worked successfully.
